CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT 0,  -- 0 代表未完成，1 代表已完成
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
